version: '3'
services:
  php:
    build:
      context: ./docker/php
    volumes:
      - ./app:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - db

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: your_password

